version: 1
disable_existing_loggers: False
formatters:
  default:
    format: '[%(asctime)s] [%(levelname)-8s] {%(name)s} | %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout
  rotating_file:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: ./logs/Weatherdan.log
    maxBytes: 100000000
    backupCount: 3
root:
  level: INFO
  handlers:
    - console
    - rotating_file
