[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[dependency-groups]
dev = [
  "pre-commit >= 4.0.1"
]
tests = [
  "pytest >= 8.3.4",
  "pytest-cov >= 6.0.0",
  "tox >= 4.23.2",
  "tox-uv >= 1.17.0"
]

[project]
authors = [
  {email = "BuriedInCode@tuta.io", name = "BuriedInCode"}
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Framework :: Pydantic :: 2",
  "Intended Audience :: End Users/Desktop",
  "License :: OSI Approved :: MIT License",
  "Natural Language :: English",
  "Operating System :: MacOS",
  "Operating System :: Microsoft :: Windows",
  "Operating System :: POSIX :: Linux",
  "Programming Language :: Python :: 3.13",
  "Typing :: Typed"
]
dependencies = [
  "fastapi[standard]>=0.115.6",
  "jinja2 >= 3.1.5",
  "pydantic >= 2.10.5",
  "ratelimit >= 2.2.1",
  "requests >= 2.32.3",
  "rich >= 13.9.4",
  "sqlmodel >= 0.0.22",
  "tomli-w >= 1.1.0",
  "uvicorn >= 0.34.0",
]
description = "Rainfall tracking system using Ecowitt."
dynamic = ["version"]
keywords = []
license = {text = "MIT"}
name = "weatherdan"
readme = "README.md"
requires-python = ">= 3.13"

[project.optional-dependencies]
postgres = [
  "psycopg >= 3.2.3"
]

[project.scripts]
Weatherdan = "run:main"

[project.urls]
Issues = "https://github.com/Buried-In-Code/Weatherdan/issues"
Source = "https://github.com/Buried-In-Code/Weatherdan"

[tool.coverage.report]
show_missing = true

[tool.coverage.run]
source = ["weatherdan"]

[tool.hatch.build.targets.sdist]
exclude = [".github/"]

[tool.hatch.version]
path = "weatherdan/__init__.py"

[tool.pytest.ini_options]
addopts = ["--cov"]

[tool.ruff]
fix = true
line-length = 100
output-format = "grouped"
show-fixes = true
unsafe-fixes = true

[tool.ruff.format]
docstring-code-format = true
line-ending = "native"
skip-magic-trailing-comma = true

[tool.ruff.lint]
ignore = [
  "COM812",
  "D",
  "DTZ",
  "FBT",
  "PLR2004",
  "TCH"
]
select = ["ALL"]

[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = true
mypy-init-return = true

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.lint.flake8-unused-arguments]
ignore-variadic-names = true

[tool.ruff.lint.isort]
combine-as-imports = true
split-on-trailing-comma = false

[tool.ruff.lint.pep8-naming]
classmethod-decorators = ["classmethod", "pydantic.field_validator"]

[tool.ruff.lint.per-file-ignores]
"weatherdan/routers/*" = ["B008"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.pyupgrade]
keep-runtime-typing = true

[tool.tomlsort]
all = true
