[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
authors = [
  { name = "BuriedInCode", email = "BuriedInCode@tuta.io" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: End Users/Desktop",
  "License :: OSI Approved :: MIT License",
  "Natural Language :: English",
  "Operating System :: MacOS",
  "Operating System :: Microsoft :: Windows",
  "Operating System :: POSIX :: Linux",
  "Programming Language :: Python :: 3.11",
  "Typing :: Typed"
]
dependencies = [
  "fastapi >= 0.85.1",
  "jinja2 >= 3.1.2",
  "pathvalidate >= 2.5.2",
  "ratelimit >= 2.2.1",
  "requests >= 2.28.1",
  "rich >= 12.6.0",
  "tomli-w >= 1.0.0",
  "uvicorn >= 0.19.0"
]
description = ""
dynamic = []
keywords = []
license = "MIT"
name = "weatherdan"
readme = "README.md"
requires-python = ">= 3.11"
version = "0.1.0b0"

[project.optional-dependencies]
dev = [
  "pre-commit >= 2.20.0",
]

[project.scripts]
ecowitt = "ecowitt.__main__:main"
importer = "importer.__main__:main"
stats = "common.statistics:print_stats"

[project.urls]
Documentation = "https://github.com/Buried-In-Code/Weatherdan#readme"
Homepage = "https://pypi.org/project/Weatherdan"
Issues = "https://github.com/Buried-In-Code/Weatherdan/issues"
Source = "https://github.com/Buried-In-Code/Weatherdan"

[tool.bandit]
recursive = true
skips = ["B101"]

[tool.black]
line-length = 100
target-version = ["py311"]

[tool.isort]
default_section = "THIRDPARTY"
line_length = 100
profile = "black"
