[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
authors = [
  {email = "BuriedInCode@tuta.io", name = "BuriedInCode"}
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: End Users/Desktop",
  "License :: OSI Approved :: MIT License",
  "Natural Language :: English",
  "Operating System :: MacOS",
  "Operating System :: Microsoft :: Windows",
  "Operating System :: POSIX :: Linux",
  "Programming Language :: Python :: 3.11",
  "Typing :: Typed"
]
dependencies = [
  "fastapi >= 0.95.0",
  "jinja2 >= 3.1.2",
  "natsort >= 8.3.1",
  "pydantic >= 1.10.7",
  "ratelimit >= 2.2.1",
  "requests >= 2.28.2",
  "rich >= 13.3.2",
  "tomli-w >= 1.0.0",
  "uvicorn >= 0.21.1"
]
description = ""
dynamic = ["version"]
keywords = []
license = {text = "MIT"}
name = "weatherdan"
readme = "README.md"
requires-python = ">= 3.11"

[project.optional-dependencies]
dev = [
  "pre-commit >= 3.2.0"
]

[project.urls]
Documentation = "https://github.com/Buried-In-Code/Weatherdan#readme"
Issues = "https://github.com/Buried-In-Code/Weatherdan/issues"
Source = "https://github.com/Buried-In-Code/Weatherdan"

[tool.black]
line-length = 100
target-version = ["py311"]

[tool.hatch.version]
path = "weatherdan/__init__.py"

[tool.ruff]
fix = true
format = "grouped"
ignore = [
  "A001",
  "A003",
  "ANN101",
  "ANN102",
  "ANN204",
  "ANN206",
  "ANN401",
  "C901",
  "RET504",
  "SIM105"
]
line-length = 100
select = [
  "A",
  "ANN",
  "ARG",
  "B",
  "BLE",
  "C40",
  "C90",
  "COM",
  # "D",
  "DJ",
  "E",
  "ERA",
  "F",
  "G",
  "I",
  "ICN",
  "INP",
  "ISC",
  "N",
  "NPY",
  "PD",
  "PGH",
  "PIE",
  "PLC",
  "PLE",
  "PLW",
  "PT",
  "PTH",
  "PYI",
  "Q",
  "RET",
  "RSE",
  "RUF",
  "S",
  "SIM",
  "SLF",
  "T10",
  "T20",
  "TCH",
  "TID",
  "UP",
  "W",
  "YTT"
]
show-fixes = true
target-version = "py311"

[tool.ruff.flake8-annotations]
allow-star-arg-any = true
mypy-init-return = true

[tool.ruff.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.isort]
combine-as-imports = true

[tool.ruff.mccabe]
max-complexity = 18

[tool.ruff.pep8-naming]
classmethod-decorators = ["classmethod", "pydantic.validator"]

[tool.ruff.per-file-ignores]
"weatherdan/routers/*" = ["ANN201", "ANN202", "B008"]
