database.url=${HOME}/.local/share/weatherdan/weatherdan.sqlite
environment=DEV
units.temp=F
units.pressure=INHG
units.wind-speed=MPH
units.rainfall=IN
units.solar-irradiance=WM2
units.capacity=L
website.host=127.0.0.1
website.port=25710
